version: "3"
services:

  #Nginx--------------------------------------------------#

  nginx:
    image: nginx:latest
    logging:
      options:
        max-size: "10m"
    container_name: nginx
    restart: on-failure:2
    depends_on:
      - notes
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${NGINX_PROJECT_DATA_PATH}:/var/www
      - ${NGINX_PROJECT_SSL_CERTIFICATES}:/etc/letsencrypt
      - ${NGINX_MAIN_PATH}:/etc/nginx
      - ${NGINX_PROJECT_CONF_PATH}:/etc/nginx/conf.d
      - ${NGINX_LOG_PATH}:/var/log/nginx
    env_file:
      - .env
    networks:
      - notes

  #Postgres-----------------------------------------------#

  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_HOST_NAME}
    volumes:
      - /home/goodwin/onedaynotedb/data/db/postgres:/var/lib/postgresql/data
      - ../tools/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - notes

  #Notes-----------------------------------------------#

  notes:
    container_name: ${NOTES_CONTAINER_NAME}
    image: ${HUB}${NOTES_IMAGE_NAME}:${NOTES_VERSION}
    ports:
      - ${NOTES_PORT}:4444
    depends_on:
      - postgres
    env_file: 
    - .env
    networks:
      - notes
networks:
  notes: