version: "3"
services:

  #Postgres-----------------------------------------------#

  postgres:
    image: postgres:10.1
    container_name: ${POSTGRES_HOST_NAME}
    volumes:
      - /home/goodwin/onedaynotedb/data/db/postgres:/var/lib/postgresql/data
      - ../tools/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - notes

  #Notes-----------------------------------------------#

  notes:
    container_name: ${NOTES_CONTAINER_NAME}
    image: ${HUB}${NOTES_IMAGE_NAME}:${NOTES_VERSION}
    ports:
      - ${NOTES_PORT}:4444
    depends_on:
      - postgres
    networks:
      - notes
networks:
  notes: