version: "3"
services:

  #Postgres-----------------------------------------------#

  postgres:
    image: postgres:10.1
    container_name: postgres
    volumes:
      - /home/goodwin/onedaynotedb/data/db/postgres:/var/lib/postgresql/data
      - ../tools/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    networks:
      - notes

  #Notes-----------------------------------------------#

  notes:
    container_name: notes
    image: mikegoodwin/notes:1.0
    ports:
      - 4444:4444
    depends_on:
      - postgres
    networks:
      - notes
networks:
  notes: