server:
  port: ${NOTES_PORT:4444}
spring:
  application:
    name: notes
#  main:
#    web-application-type: none
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST_NAME:postgres}:${POSTGRES_PORT:5432}/notes
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.yandex.ru
    port: 587
    username: ${NOTES_MAIL_USERNAME:notify@onedaynote.online}
    password: ${NOTES_MAIL_PASSWORD:generatedpass}
    properties.mail.smtp:
      ssl.enable: true
      timeout: 5
      starttls.enable: true
