server:
  port: 4444
spring:
  application:
    name: notes
#  main:
#    web-application-type: none
  datasource:
    url: jdbc:postgresql://postgres:5432/notes
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
#  redis:
#    host: ${REDIS_HOST:redis}
#    port: ${REDIS_PORT:6379}
#    username: ${REDIS_USERNAME:redis}
#    password: ${REDIS_PASSWORD:password}
#    hashKey: 'NOTES'
  mail:
    host: smtp.yandex.ru
    port: 587
    username: ${MAIL_USERNAME:notify@onedaynote.online}
    password: ${MAIL_PASSWORD:generatedpass}
    properties.mail.smtp:
      ssl.enable: true
      timeout: 5
      starttls.enable: true
