openapi: 3.0.0
info:
  title: api
  version: '1.0'
servers:
  - url: 'http://onedaynote.online'
paths: {}
components:
  schemas:
    NoteCreate:
      title: NoteCreate
      type: object
      properties:
        type:
          type: integer
          enum:
            - '0:TEXT'
            - '1:PICTURE'
            - '2:PICTURE_WITH_TEXT'
        key:
          type: string
        payload:
          type: string
        extraPayload:
          type: string
        definition:
          type: string
        color:
          type: string
        animal:
          type: string
        action:
          type: string
        removable:
          type: boolean
        notifyEmail:
          type: string
      x-examples:
        example-1:
          type: '0:TEXT'
          key: string
          payload: string
          extraPayload: string
          definition: string
          color: string
          animal: string
          action: string
          removable: true
          notifyEmail: string
    NoteDtoFull:
      title: NoteDtoFull
      type: object
      properties:
        id:
          type: integer
        type:
          type: integer
          enum:
            - '0:TEXT'
            - '1:PICTURE'
            - '2:PICTURE_WITH_TEXT'
        payload:
          type: string
        extraPayload:
          type: string
        created:
          type: string
          format: date-time
